### ISSUE TITLE
ios 17 and iphone 14 problem

### ISSUE THREAD

**Issue by admin22312** [culturally/Instagram-iOS-SSL-pinning-bypass#1]
there is a problem on the iPhone 14 pro max with iOS 17 that during the first installation I saw requests before logging in, then the application crashed, after which it only wrote an error, I used Sideloadly and burpsuite

**Comment by culturally** [comment]
> there is a problem on the iPhone 14 pro max with iOS 17 that during the first installation I saw requests before logging in, then the application crashed, after which it only wrote an error, I used Sideloadly and burpsuite

Interesting, I've never encoutered an issue. Also it could've been iOS or any other application requests. Try something else other then Sideloadly i personaly used trollstore + mitmproxy

**Comment by admin22312** [comment]
> > на айфоне 14 про макс с iOS 17 такая проблема, что при первой установке видел запросы перед входом в систему, потом приложение вылетало, после чего только писало ошибку, я использовал Sideloadly и burpsuite
> 
> Интересно, я никогда не сталкивался с проблемой. Также это могли быть запросы iOS или любого другого приложения. Попробуйте что-нибудь еще, кроме Sideloadly, я лично использовал trollstore + mitmproxy.

Regarding the trollstore - 16.7.x (excluding 16.7 RC) and 17.0.1+ will NEVER be supported (unless a third CoreTrust bug is discovered, which is unlikely).
I'll try, but as far as I understand, this is not a problem with the interception program, but a problem with the IPA itself

**Comment by culturally** [comment]
Can you try to intercept with mitmproxy? also it shouldn’t be an IPA issue maybe if the versions would be different for iOS 17 which i doubt because i have used iOS 15 and 16 with the IPA and it worked without any issues

**Comment by admin22312** [comment]
> Can you try to intercept with mitmproxy? also it shouldn’t be an IPA issue maybe if the versions would be different for iOS 17 which i doubt because i have used iOS 15 and 16 with the IPA and it worked without any issues

![1](https://github.com/culturally/Instagram-iOS-SSL-pinning-bypass/assets/122495192/999655ab-607d-4e0a-8d91-5c21907a9a48)
The problem with closing after authorization now remains with mitmproxy
IOS 17.4.1
Iphone 14 pro max
