### ISSUE TITLE
Not working both iOS 17.6.1 & iOS 15.7.6

### ISSUE THREAD

**Issue by cuzv** [culturally/Instagram-iOS-SSL-pinning-bypass#2]
My iPhone system is 17.6.1, and the iPad system is iOS 15.7.6, neither of which can be used successfully.

![Screenshot 2024-09-14 at 21 42 58](https://github.com/user-attachments/assets/108afd03-51fc-48eb-b488-f07cf3f532c9)

<img width="393" alt="image" src="https://github.com/user-attachments/assets/a179e91f-7191-4865-a461-2830bc4807bc">

Any suggestions? Thanks.

**Comment by culturally** [comment]
> My iPhone system is 17.6.1, and the iPad system is iOS 15.7.6, neither of which can be used successfully.
> 
> 
> 
> ![Screenshot 2024-09-14 at 21 42 58](https://github.com/user-attachments/assets/108afd03-51fc-48eb-b488-f07cf3f532c9)
> 
> 
> 
> <img width="393" alt="image" src="https://github.com/user-attachments/assets/a179e91f-7191-4865-a461-2830bc4807bc">
> 
> 
> 
> Any suggestions? Thanks.

try older version also make sure you setup proxy before intercepting sometimes it takes a while tbh i can't do nothing about it last time i tried it was kinda buggy but it worked

**Comment by cuzv** [comment]
Thank you for your quick reply.

The screenshot I took was without a proxy setup. Once I set up the proxy (mitmproxy and proxyman), no traffic from the Instagram App is intercepted, and it indicates a connection anomaly. Any clues?

<img width="515" alt="image" src="https://github.com/user-attachments/assets/386b5052-b090-4ba8-aadd-cef33cb94645">

**Comment by culturally** [comment]
i have no idea
